apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: sealedsecret
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.12.1/controller.yaml
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/