apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: psg-secret
  namespace: default
spec:
  encryptedData:
    PASSWORD: AgBRkoeoS4tI5NYmLFK3lpcRbHseDOb/FsQz9z0Vk3ClENejFI5LcsMYU/kVgRoFNqczcuW10Bgb5TUfkThGbD+BDM/OFbwrDEFu9R7kaOHyzDSK6AO5Vg+RmowQebRam6c1E1ESkJNl5ysOHATzkdKMrBbF1xcEA4Dh0fY+stRo5xqXddq4j114HUEBb2c9GsnGHMBXzjJC361eqTHlwpX5E9+rT2/xorLWws7NmMmEdfi3D+am/Iw9wEVsbjrctTkrPV2spVELn7enuFw9+EDsBPHL2VGCtcZvWPfk14v51bXbqaAY17PbDU02nuzW5stsplZKhFrRWyumkNyJBeOno05zXuKsmS3cmlkapUCLmZhSYQKvOKO5bs+qLKm+zbf9lLVjrGa7diLNRzdYW0SZIu8QG9Ll7yuxrbUeI7ok4NJa2miypKJ3gDah/aM2O1MTxrgadZBFRp6A6zwSFmbpu2V5rDTQmBbtJZtSY5wIZoEHNWUKkUoScvm74PtA3rqPqMNhfUoX9oR/LAssb2Om8yKoWxld6+SjcVRRY6byfSHOCKHe4uAge3vPFPyJFk2f4PxAxUCTEekeWYVai/DUQfRX1Gxt9VhRfz8LobVcG018yEwgFN/VYzrInfzi8oZPlEkHfi2XPKRYokuyOzOvlFmIPX0X13jRmw6uHtFl9ETlLNILDw7MdKXY3VO8LjOOY9Pp8lg=
  template:
    metadata:
      creationTimestamp: null
      name: psg-secret
      namespace: default

